// Roteiros de TELEPROMPTER do curso "Cybersegurança e LGPD no VibeCoding".
// key do slide → texto de fala (tom natural, descontraído, 1ª pessoa).
// Exibido pelo overlay de teleprompter (tecla T). Não aparece na gravação se desligado.

export const scripts: Record<string, string> = {
  // ─── INTRO ───
  cover: `Olá, seja muito bem-vindo! Que bom te ver aqui. Esse é o curso Cybersegurança e LGPD no VibeCoding, e a ideia é simples: te levar do protótipo ao SaaS seguro, sem juridiquês. Olha, se você cria apps com Lovable, Cursor, essas ferramentas de IA, esse curso é pra você. No final, você vai saber enxergar onde seu app vaza, fechar os buracos do banco de dados e entender a LGPD de um jeito que cabe no seu código, não num contrato chato. Bora começar.`,
  agenda: `Deixa eu te mostrar a jornada. São dez aulas. A gente começa pelo risco invisível, entende Supabase e RLS, e bota a RLS na prática. Depois entra em código e governança, LGPD sem juridiquês, base legal, transparência e papéis. Aí a gente vê quanto custa ignorar tudo isso, como a LGPD vira código de verdade, e fecha com o arsenal e a arquitetura. Beleza? É essa a estrada. Vem comigo.`,

  // ─── AULA 1 ───
  aula_1: `Aula um de dez: o risco invisível. Aqui o papo é sobre construir rápido sem deixar buracos. Porque dá pra ter as duas coisas, sacou? Velocidade e segurança. Bora entender por onde tudo começa.`,
  vibe_coding_oque: `Então, o que é vibe coding? É isso: você descreve em linguagem natural o que quer, e as ferramentas, Lovable, Cursor, v0, escrevem o código pra você. A velocidade é absurda. Dá pra ter um app no ar num fim de semana, de verdade. Só que o risco vem junto, e é aí que mora o perigo. A IA otimiza pra funcionar, não pra ser segura. Ela faz a feature rodar bonito, mas não pensa em quem tá tentando arrombar a porta. E essa parte fica por sua conta.`,
  realidade: `Olha esse dado, porque ele assusta. A maioria das apps geradas com IA que estão em produção tem RLS aberto. Traduzindo: o cadeado do banco de dados está destrancado. Qualquer um que souber onde bater consegue ler, mudar ou apagar os dados. E o pior é que parece tudo certo, o app funciona normal. O buraco tá lá, só que invisível. Por isso esse é o ponto de partida do curso.`,
  historia_real: `Deixa eu te contar como isso vaza na vida real. Sexta-feira você lança o app no grupo do zap, todo feliz. Sábado já tem duzentos cadastros, com CPF e tudo. Domingo alguém curioso abre o DevTools do navegador e percebe que dá pra puxar a tabela toda. E segunda-feira aquela base inteira tá circulando num fórum por aí. Não é filme de terror, é o roteiro mais comum que existe.`,
  policy_faltando: `E sabe o que tava por trás de tudo isso? Uma policy faltando. Só isso. Uma regrinha de acesso que ninguém configurou.`,
  porque_acontece: `Por que a IA deixa a porta aberta? Quatro motivos. Primeiro, o default já vem permissivo, aberto de fábrica. Segundo, você pediu a feature, não pediu a trava de segurança, e a IA entrega exatamente o que você pede. Terceiro, ninguém revisa o que a IA gerou, a gente confia e segue em frente. E quarto, segurança é invisível: tudo parece funcionar perfeitamente até o dia que vaza. Por isso o olhar tem que ser seu, desde o começo.`,
  tres_camadas: `Pra organizar a cabeça, pensa em três camadas de risco. A primeira é o banco: RLS, edge functions, RPC, é onde os dados moram. A segunda é o código: secrets que vazam, validação que falta, logs que contam demais. E a terceira é a governança: LGPD, quem tem acesso ao quê, e backup. O curso inteiro vai passear por essas três camadas. Se você guardar esse mapa, já tá com meio caminho andado.`,
  aula1_recap: `O que levar dessa aula? Três coisas. Vibe coding é rápido e perigoso por padrão. A maioria dos vazamentos acontece pelo banco de dados. E o risco mora em três camadas: banco, código e governança. Na próxima aula a gente mergulha no Supabase e na tal da RLS. Te vejo lá.`,

  // ─── AULA 2 ───
  aula_2: `Bom, agora a gente entra na aula dois de dez. E essa aqui é uma das mais importantes. Por quê? Porque é no Supabase que mora oitenta por cento do risco. É lá que o dado vive, é lá que as regras valem ou não valem. Então presta atenção.`,
  supabase_oque: `Deixa eu te explicar rapidinho o que é o Supabase. É o backend que já vem prontinho pra você. Ele te dá quatro coisas. Primeiro, um banco PostgreSQL, que é onde os teus dados moram de verdade. Segundo, o auth, que cuida de login e de sessão. Terceiro, o storage, que guarda os arquivos. E quarto, as edge functions, que é código rodando no servidor sob demanda. Você não precisa montar nada disso na mão. Mas é justamente por vir pronto que a gente precisa entender como cada pedaço funciona.`,
  vitrine_deposito: `Sabe aquela comparação que ajuda a fixar? Pensa assim. O Lovable é a vitrine, o Supabase é o depósito. A vitrine é o que o usuário vê, a interface, o estado da tela, os fluxos do front. É o que está exposto. Já o depósito é onde o dado realmente fica guardado, o banco, o auth, as edge, o storage. É ali que as regras vivem. E sacou uma coisa? Proteger só a vitrine não adianta nada se o depósito tá de porta aberta.`,
  tres_pilares: `Dentro do Supabase tem três pilares que você precisa ter no radar. O primeiro são as tabelas, e o risco aqui é deixar o RLS aberto. O segundo são as edge functions, e o risco é não validar o JWT, ou seja, não checar quem tá chamando. E o terceiro são as RPCs, onde o perigo é o SECURITY DEFINER cego, que roda com permissão total sem olhar quem pediu. Guarda esses três, porque é onde quase todo vazamento começa.`,
  anon_vs_service: `Agora presta muita atenção nessas duas chaves, porque confundir elas é desastre. A anon key é pública, ela vai pro front, qualquer visitante consegue ver ela no navegador. E tudo bem, porque ela respeita o RLS. Por isso o teu RLS precisa estar certo, porque é ele que segura essa chave. Já a service_role é secreta, e ela nunca, jamais, pode ir pro front. Ela ignora o RLS, tem acesso total ao banco. Ela só vive em edge function ou no servidor. Se essa daqui vazar, entregaram o banco inteiro de bandeja.`,
  o_que_e_rls: `Então vamo falar do RLS de verdade. RLS é row level security, que em bom português é a regra que define quem vê qual linha do teu banco. E ela funciona em quatro operações. SELECT, que decide quem pode ver. INSERT, que decide quem pode criar. UPDATE, que decide quem pode editar. E DELETE, que decide quem pode apagar. Cada uma dessas precisa de uma regra. Não basta proteger o ver e esquecer do apagar, entendeu? É linha por linha, operação por operação.`,
  rls_aberto: `E é aqui que mora o perigo. Imagina um cadeado totalmente aberto. RLS desativado é exatamente isso, é porta escancarada. Qualquer um que tenha a anon key, e lembra, ela tá lá no front, visível pra todo mundo, consegue ler o teu banco inteiro. Sem login, sem nada. É o erro mais comum e o mais caro que dá pra cometer no Supabase.`,
  aula2_recap: `Então bora fechar essa aula. Primeiro, o Supabase é o depósito, é onde o dado mora de verdade. Segundo, a anon key é pública e respeita o RLS, enquanto a service_role ignora tudo e por isso nunca vai pro front. E terceiro, RLS desativado é banco aberto pra qualquer um. Na próxima a gente arregaça a manga e configura RLS na prática.`,

  // ─── AULA 3 ───
  aula_3: `Aula três de dez: RLS na prática. Chega de teoria, agora a gente vai botar a mão no código e configurar a tua tabela do jeito certo. Calma que é mais simples do que parece.`,
  rls_como_ativar: `O primeiro passo é sempre esse: ativar o RLS na tabela. Esse comando aqui, enable row level security, é o que liga o cadeado. E olha que interessante: assim que você ativa, ninguém mais lê nada. Nada mesmo. A tabela fica trancada pra todo mundo até você criar uma policy que libere alguém. Pode parecer estranho travar tudo, mas esse é o ponto de partida seguro. Você abre só o que precisa, na medida certa, em vez de deixar tudo aberto e tentar fechar depois.`,
  policy_anatomia: `Toda policy, toda regra de acesso, tem quatro peças. Vale a pena decorar. O FOR diz qual ação a regra cobre: select, insert, update ou delete. O TO diz pra qual papel ela vale: authenticated, que é o usuário logado, ou anon, o visitante. O USING define quais linhas a pessoa pode ver ou mexer. E o WITH CHECK define o que ela pode gravar. Guarda essa diferença: USING é leitura, WITH CHECK é escrita. Daqui a pouco isso vai fazer total sentido.`,
  top_riscos_rls: `Esses são os quatro erros mais comuns de RLS, e olha, eu vejo todos eles toda semana. Um: RLS desativado na tabela, aí qualquer um lê tudo. Dois: política com select igual a true, que libera o público a ver dado privado. Três: insert sem validar o user_id, e o sujeito grava registro no nome de outra pessoa. E quatro: update ou delete sem checar o dono, então alguém edita ou apaga dado alheio. Vamo ver na prática como o certo e o errado se parecem.`,
  exemplo_ruim: `Olha esse exemplo, porque ele é uma porta aberta escancarada. A policy diz: for select, using true. Traduzindo o using true: qualquer um, autenticado ou não, vê tudo. Você criou achando bonito porque funcionou, o app mostrou os dados, beleza. Só que funciona pro atacante também. Ele pega a anon key, faz a mesma consulta, e leva a tabela inteira. Esse using true é o vilão número um. Se você só fixar uma coisa dessa aula, fixa: nunca, jamais, using true numa tabela com dado de gente.`,
  exemplo_bom: `Agora o jeito certo. Mesma tabela, mas a policy diz: for select, to authenticated, using user_id igual a auth ponto uid. O auth ponto uid é o id do usuário que está logado naquele momento. Então a regra compara: a linha é desse usuário? Se bater, ele vê. Se não bater, some. Cada um enxerga só o que é dele, automaticamente, sem você filtrar nada no front. É curto, é elegante, e fecha o buraco. É esse o padrão que você quer repetir em toda tabela.`,
  insert_check: `Esse aqui é o erro que quase todo mundo esquece. No insert, a trava não é o using, é o WITH CHECK. Olha a policy: for insert, to authenticated, with check user_id igual a auth ponto uid. Sem isso, eu consigo gravar um pedido no seu nome, só mudando o user_id na requisição. Com o with check, o banco recusa qualquer insert que não seja do próprio usuário. Lembra do que eu falei? USING controla o que ele lê, WITH CHECK controla o que ele grava. Insert precisa do check, sempre.`,
  teste_rls: `E como você sabe se o RLS tá de pé mesmo? Testa. Pega a anon key, que tá ali no teu próprio front, e tenta ler a tabela direto, sem login. Pode ser pelo curl, pelo Postman ou pelo próprio painel. A regra é simples: deslogado, você não pode ver nada de ninguém. Se aparecer dado, tem buraco. E pra facilitar, roda o Security Advisor do Supabase, que aponta tabela sem RLS em dois minutos, de graça. Testar leva cinco minutos e evita uma dor de cabeça gigante.`,
  aula3_recap: `Fechando a aula. Ative o RLS primeiro e libere depois com as policies, uma de cada vez. Lembra da dupla: USING controla a leitura, WITH CHECK controla a escrita. E sempre teste com a anon key deslogado, mais o Security Advisor. Na próxima a gente sai do banco e olha o resto do código.`,

  // ─── AULA 4 ───
  aula_4: `Aula quatro de dez: código e governança. A gente blindou o banco, mas o risco não mora só lá. Tem coisa importante no teu código e na forma como você organiza acesso. Bora ver.`,
  codigo_vs_supabase: `Antes de tudo, deixa eu separar onde mora cada coisa, porque isso confunde muita gente. No código, ou seja, no front e nas edge functions do Lovable, ficam: a validação de input, os secrets via variável de ambiente, o rate limit das edge e os logs sem dado sensível. Já no banco, no Supabase, ficam as regras de acesso: o RLS por tabela, as RPCs, o auth e os backups. São dois territórios. E pra ter um app seguro, você precisa cuidar dos dois, não dá pra escolher só um.`,
  secrets_front_edge: `Esse é o vazamento mais bobo e, ao mesmo tempo, o mais comum. Onde guardar uma chave de API? Se você bota a chave no código do front, ela vai pro navegador dentro do bundle. Qualquer um abre o DevTools e lê. Sua chave da Stripe, da OpenAI, do serviço de e-mail, tudo exposto, rodando na sua conta e na sua fatura. O jeito certo é deixar a chave só no servidor: o front chama a edge function, e a edge usa a chave. Ela nunca chega ao navegador. O cliente nem sabe que ela existe.`,
  edge_valida_jwt: `Edge function é a tua primeira linha de defesa, mas só se você usar direito. Olha o código: a gente pega o usuário a partir do JWT, com o getUser, e se não tiver usuário, devolve 401, não autorizado. Só passa daqui quem tá logado de verdade. Parece óbvio, mas uma edge function exposta sem essa checagem é, na prática, um endpoint público que qualquer um chama. Então grava: valide quem está chamando antes de fazer qualquer coisa. Sempre.`,
  validacao_input: `E uma regra de ouro: nunca confie no que chega do cliente. Valide tipo, tamanho e formato de tudo, de preferência com uma biblioteca como o zod, no servidor. Por quê? Porque o front pode ser burlado fácil: DevTools, curl, uma requisição forjada na mão. Então valores sensíveis, tipo preço, o papel do usuário, o user_id, você sempre checa no server. Nunca aceita de boa o que o client mandou. O front é sugestão, o server é a lei.`,
  nao_so_lovable: `O Lovable ajuda muito, mas ele não faz tudo sozinho. Quatro hábitos que valem ouro. Um: audite você mesmo com IA, cola teu código no Claude ou no GPT, eles leem melhor que a gente. Dois: o GitHub é tua rede de segurança, histórico, rollback, code review. Três: service_role nunca no front, só a anon key vai pro client. E quatro: roda o Security Advisor do Supabase toda semana, é grátis. São hábitos simples que separam o app amador do profissional.`,
  logs_pii: `E pra fechar a parte de código, um lembrete que pouca gente lembra: log não é lixeira de dado pessoal.`,
  aula4_recap: `Resumindo a aula. Secret fica só no servidor, nunca no bundle do front. Toda edge function valida o usuário antes de qualquer coisa. E você valida todo input no server, além de não jogar PII nos logs. Guardou? Então bora pra LGPD, que é onde a coisa fica jurídica, mas eu prometo, sem juridiquês.`,

  // ─── AULA 5 ───
  aula_5: `Aula cinco de dez: LGPD sem juridiquês. Eu sei, eu sei, só de ouvir LGPD já dá um arrepio. Mas relaxa, eu vou te explicar de um jeito que faz sentido pra quem programa. Sem decoreba de artigo.`,
  lgpd_porque_voce: `Sabe o que eu mais ouço? Ah, é só um MVP de fim de semana, a LGPD não é comigo. Olha, sinto te dizer: se você tratou o dado de um único brasileiro, você já está sob a lei. Não existe exceção de tamanho. Não tem aquele de é pequeno então não conta. Cinco usuários ou cinco milhões, vale igual. Então melhor já começar do jeito certo.`,
  lgpd_o_que_e: `Então, na real, o que é a LGPD? É a lei treze mil setecentos e nove, de dois mil e dezoito, a lei geral de proteção de dados do Brasil. Ela foi inspirada no GDPR, que é o padrão europeu que virou referência no mundo todo. Ela criou a ANPD, que é a autoridade que fiscaliza, orienta e, quando precisa, multa. E o ponto que importa pra você: tratou dado de brasileiro, está sob a LGPD. Mesmo que seja só o teu MVP.`,
  lgpd_glossario: `Quatro palavrinhas que você vai me ouvir falar o curso todo, então vale fixar agora. Titular é a pessoa dona do dado, ou seja, o teu usuário. Tratamento é qualquer uso do dado: coletar, guardar, mostrar, apagar, tudo é tratamento. Dado pessoal é tudo que identifica alguém. E ANPD é a autoridade que fiscaliza e multa. Pronto, com essas quatro você já fala a língua da lei.`,
  lgpd_linha_tempo: `Rapidinho, a linha do tempo pra você situar. Em dois mil e dezoito a lei foi sancionada. Em dois mil e vinte ela entrou em vigor, passou a valer de verdade. E em dois mil e vinte e um as sanções começaram a pegar, ou seja, a ANPD passou a poder multar. Então não é coisa nova nem promessa futura, já tá valendo faz tempo.`,
  lgpd_dado_sensivel: `Uma coisa importante: nem todo dado é igual. Tem o dado pessoal, que identifica a pessoa, tipo nome, e-mail, telefone, CPF, endereço, IP, cookie. E tem o dado sensível, que tem um regime reforçado, uma proteção mais pesada. Isso é saúde, dado genético, biometria, tipo face e digital, raça, religião, posição política, orientação sexual. Se um dado sensível vaza, o estrago e a multa são muito maiores. Então se o teu app lida com isso, redobra o cuidado.`,
  lgpd_pii_escondida: `E olha, você coleta muito mais dado pessoal do que imagina. Tem a PII escondida. O IP e o user agent, por exemplo, todo request loga, mesmo de quem nem cadastrou. A geolocalização, naquele popup de permitir localização. O device id, que vem de analytics, push, fingerprint. E claro, e-mail e nome, que é o óbvio, mas continua sendo PII. Faz um exercício depois: lista tudo que o teu app coleta. Vai te surpreender.`,
  aula5_recap: `Fechando. Tratou dado de brasileiro, a LGPD vale, até no MVP de fim de semana. Dado sensível, tipo saúde e biometria, tem regime reforçado. E você coleta mais PII do que pensa: IP, device, localização. Na próxima a gente ataca o coração da lei, a tal da base legal.`,

  // ─── AULA 6 ───
  aula_6: `Aula seis de dez: base legal, o coração da LGPD. Essa aqui é a aula que desfaz o maior mito sobre a lei. Presta atenção que vai clarear muita coisa na tua cabeça.`,
  lgpd_mito: `Vou começar quebrando o mito número um: LGPD não é só pedir consentimento. Aquele popozinho de aceito os cookies? Então, não é só isso, longe disso.`,
  lgpd_10_bases: `Olha só, no artigo sétimo da lei existem dez bases legais. Dez. O consentimento é só uma delas. Tem execução de contrato, obrigação legal, legítimo interesse, proteção da vida, tutela da saúde, exercício de direitos, política pública, estudo e pesquisa, e proteção ao crédito. Não precisa decorar todas. O importante é entender que consentimento é uma entre dez, e quase nunca é a que você vai usar no dia a dia do teu SaaS.`,
  lgpd_bases_legais: `Das dez bases, três importam de verdade no teu SaaS. A principal é execução de contrato: o dado é necessário pra entregar o serviço, ponto. Depois vem o legítimo interesse, pra usos esperados, tipo segurança, antifraude e logs. E só então o consentimento, que é pro extra, o opcional, marketing e cookies. Sacou a ordem? Consentimento é a última, não a primeira. A maioria do que você coleta cai em execução de contrato.`,
  lgpd_teste_contrato: `E como saber se é execução de contrato? Tem um teste simples, faz essa pergunta: se eu parar de tratar esse dado, eu ainda consigo prestar o serviço? Se a resposta é não, então a base é execução de contrato, e você não precisa de consentimento pra isso. Guarda essa pergunta, ela resolve oitenta por cento das tuas dúvidas.`,
  lgpd_exemplos_base: `Vamo na prática, qual base usar pra cada dado. E-mail e senha? Execução de contrato, sem isso não tem login. CPF na nota fiscal? Execução de contrato. Endereço de entrega? Execução de contrato também. Logs, IP, antifraude? Legítimo interesse. Agora, newsletter e marketing? Aí sim, consentimento. E compartilhar com um parceiro? Consentimento na veia. Viu como a maioria nem precisa de consentimento? Isso muda tudo na forma como você desenha o app.`,
  lgpd_aws_q: `Deixa eu te fazer uma pergunta provocativa. Quem aí acha que a AWS precisa do seu consentimento pra guardar o e-mail do seu login? Pensa um segundo.`,
  lgpd_aws_a: `Resposta: se precisasse, a internet não funcionaria. Imagina um popup de aceite a cada servidor que toca no teu dado. Não rola. É execução de contrato puro.`,
  lgpd_frase_efeito: `Então grava essa frase, porque ela resume a aula: a LGPD não exige consentimento. Ela exige base legal válida. São coisas diferentes.`,
  aula6_recap: `Resumo da aula. Existem dez bases legais, e o consentimento é só uma. No teu SaaS, a maior parte do dado é execução de contrato. E o teste mágico é: sem esse dado, eu ainda entrego o serviço? Próxima aula: transparência e os papéis, controlador e operador.`,

  // ─── AULA 7 ───
  aula_7: `Aula sete de dez: transparência e papéis. A gente viu que nem sempre precisa de consentimento. Mas atenção, isso não te dá carta branca. Tem responsabilidade junto. Bora entender.`,
  lgpd_onde_mora_risco: `Primeiro, onde mora o risco de verdade na LGPD. Não é coletar o e-mail pra logar, relaxa. O risco é usar a base de dados pra marketing não relacionado, compartilhar com parceiro comercial sem avisar, treinar uma IA própria com o dado do cliente, ou qualquer uso que o usuário não espera. Essa é a palavra-chave: o que o usuário não espera. Se ele ficaria surpreso ou bravo ao descobrir, acende o alerta.`,
  lgpd_transparencia: `E aqui um ponto que confunde muita gente: não precisar de consentimento não é o mesmo que poder esconder. O erro é pensar, ah, não preciso de consentimento, então nem aviso. Errado. O certo é informar com clareza: você fala que coleta, conta a base legal, mantém uma política de privacidade clara e garante os direitos do titular. Você não precisa pedir aceite pra tudo, mas você precisa ser transparente sobre tudo. Transparência é sempre obrigatória.`,
  politica_privacidade: `Então, o mínimo que a tua política de privacidade precisa ter. Quais dados você coleta e de onde vêm. Pra quê e com qual base legal, ou seja, a finalidade de cada tratamento. Com quem você compartilha, e aqui entra Supabase, Stripe, ferramentas de analytics. E por fim, como a pessoa exerce os direitos dela, mais um contato do encarregado, um canal de verdade. Não precisa ser um documento de advogado de cinquenta páginas. Precisa ser claro e honesto.`,
  lgpd_controlador_operador: `Agora o tema que todo SaaS confunde: controlador e operador. O controlador é quem decide o porquê e o como do tratamento. Exemplo: a escola que cadastra os alunos, ela define a finalidade e responde por aquilo. Já o operador trata o dado em nome do controlador, segue as instruções dele. Geralmente o teu SaaS é o operador, processando o dado do teu cliente. Mas atenção: você vira controlador se usar aquele dado pra analytics ou IA próprios. E dá pra ser os dois ao mesmo tempo.`,
  lgpd_basico: `Resumindo por que levar isso a sério. Se você guarda dado de brasileiro, a LGPD vale pra você. Na prática, o que muda no teu app: escolher a base legal certa, informar o que coleta e por quê, e responder os pedidos do titular. E se ignorar? A multa da ANPD pode chegar a dois por cento do faturamento, com teto de cinquenta milhões por infração. Fora bloqueio do tratamento e dano moral coletivo. Não é só susto, é conta de verdade.`,
  aula7_recap: `Fechando. Não pedir consentimento não te deixa esconder nada. Transparência é sempre obrigatória, então tenha uma política clara. E lembra: você costuma ser o operador, mas vira controlador na hora que usa o dado pra você mesmo. Na próxima aula, a parte que dói no bolso: quanto custa ignorar tudo isso.`,

  // ─── AULA 8 ───
  aula_8: `Aula oito de dez: quanto custa ignorar. Até agora eu falei dos conceitos. Agora deixa eu te mostrar a conta, com casos reais. Porque isso aqui vira manchete, e vira rápido.`,
  lgpd_quanto_custa: `Ignorar proteção de dados tem preço. E não é só multa, é a tua marca estampada no jornal. Bora ver alguns números pra dimensionar.`,
  lgpd_multa_recorde: `Esse é o recorde. A maior multa de proteção de dados da história: um vírgula dois bilhão de euros. Foi a Meta, em dois mil e vinte e três, por mandar dados de europeus pros Estados Unidos sem base legal. Um vírgula dois bilhão de euros. Lê de novo esse número. É o tamanho do estrago quando uma empresa gigante trata o tema com descaso.`,
  lgpd_casos_reais: `E não foi caso isolado, olha esses outros. Meta, um vírgula dois bilhão de euros, por transferir dado de europeu sem base legal. Amazon, setecentos e quarenta e seis milhões de euros, por publicidade sem consentimento válido. TikTok, trezentos e quarenta e cinco milhões, por dado de criança mal protegido. E aqui no Brasil, a Telekall, quatorze mil e quatrocentos reais, por vender lista de WhatsApp, a primeira multa da ANPD, em dois mil e vinte e três. Os números variam, mas o recado é o mesmo.`,
  lgpd_brasil_hoje: `E no Brasil, como tá? A multa ainda é tímida, mas o estrago não. A fiscalização da ANPD ainda tá amadurecendo: a primeira multa foi só em dois mil e vinte e três, aqueles quatorze mil reais, e ela já puniu falta de encarregado e de atender direitos. De dois mil e vinte e quatro pra cá, endureceu. Mas olha o que dói de verdade: a Serasa teve mais de duzentos e vinte milhões de CPFs vazados em dois mil e vinte e um. Tem ação civil, dano moral coletivo, e reputação destruída num único print. O vazamento não espera a ANPD pra te machucar.`,
  anpd_sancoes: `E não é só multa que a ANPD pode aplicar. Tem quatro tipos de sanção. A advertência, com prazo pra você corrigir. A multa, até dois por cento do faturamento, teto de cinquenta milhões por infração. O bloqueio ou a eliminação do dado tratado de forma irregular, imagina ter que apagar a tua base. E a publicização, que é tornar a infração pública, ou seja, o tombo de imagem na frente de todo mundo. Às vezes esse último machuca mais que o cheque.`,
  aula8_recap: `Resumindo a aula. Lá fora as multas chegam a um vírgula dois bilhão de euros. No Brasil a multa ainda é menor, mas a sanção vai muito além dela. E o mais importante: o vazamento te machuca antes mesmo da ANPD, na reputação e na ação civil. Na próxima, a boa notícia: como transformar a LGPD em código.`,

  // ─── AULA 9 ───
  aula_9: `Aula nove de dez: LGPD vira código. Chega de teoria jurídica, agora a melhor parte pra gente que programa. Como cada exigência da lei vira um pedaço de código no teu app. Bora.`,
  lgpd_cyber: `Uma frase pra abrir a cabeça: LGPD é governança de dados. E sem cybersecurity, ela não existe na prática. De que adianta a política linda no papel se o banco tá de porta aberta? Os dois andam juntos, sempre.`,
  direitos_titular: `O artigo dezoito da lei dá seis direitos ao titular, e cada um deles vira funcionalidade no teu app. Acessar: ver tudo que você tem dele. Corrigir: atualizar dado errado. Portar: exportar pra outro serviço. Revogar: tirar o consentimento. Excluir: apagar a conta e os dados. E revisar decisão automatizada: contestar o que a IA decidiu sobre ele. Olha que interessante, cada direito desses é um botão, um endpoint, uma tela. A lei vira backlog.`,
  lgpd_vira_codigo: `Na prática, como cada coisa vira código no Supabase. Exclusão: uma edge function que apaga a conta e os dados. Portabilidade: um endpoint de export, em JSON ou CSV. Minimização: não logar PII e usar views mascaradas. Consentimento: uma tabela de consents, com timestamp e versão, pra você provar quando e o que a pessoa aceitou. E incidente: um alerta que dispara pra você avisar a ANPD e os titulares. Viu? Tudo isso é código que você já sabe escrever.`,
  delete_conta_code: `Vamo ver o direito de exclusão em código, que é o que mais pega gente. Quando o usuário pede apaga minha conta, isso precisa funcionar de verdade. Olha a edge function: a gente deleta os pedidos dele, deleta o perfil, e por fim apaga o próprio usuário do auth. Some de tudo. O erro clássico é só marcar como inativo e continuar guardando o dado. Isso não cumpre o direito. Excluir é apagar mesmo, de verdade.`,
  incidente_plano: `E se vazar? Você precisa de um plano de incidente, e o segredo é montar ele antes de precisar. Quatro passos. Detectar e conter, com logs e alertas que avisam rápido. Avaliar o risco: quem foi afetado e qual dado. Comunicar a ANPD e os titulares, em prazo razoável, e aqui é quanto antes melhor. E registrar tudo: o que aconteceu e o que você fez. No susto a gente trava, então é o plano pronto na gaveta que salva.`,
  governanca_acessos: `Pra fechar, governança: quem acessa o quê. Uma matriz mínima de papéis. O vendedor vê só os leads dele, então RLS por owner_id. O gerente vê o time todo e exporta relatório, um papel manager. O marketing precisa de e-mail e tag, mas não de CPF nem valor de negócio, então view mascarada e read-only. E você, o builder, tem o service_role, que é bypass total da RLS, então MFA ligado e essa chave só na edge, nunca no client. Cada um com o mínimo que precisa.`,
  aula9_recap: `Resumindo. Cada direito do titular vira um endpoint no teu app. Excluir é apagar de verdade, não marcar como inativo. E tenha um plano de incidente pronto antes de precisar dele. Última aula agora: o arsenal de ferramentas e como pensar a arquitetura pra escalar com segurança.`,

  // ─── AULA 10 ───
  aula_10: `Chegamos na aula dez de dez: arsenal e arquitetura. Reta final. Agora eu te entrego as ferramentas pra você se defender e os próximos passos pra crescer sem perder o sono. Bora fechar com chave de ouro.`,
  ferramentas_principais: `Deixa eu te mostrar a artilharia pesada de dois mil e vinte e seis. De um lado, o AWS Security Agent, que já tá disponível: é um pentest autônomo, multi-agente, que explora, valida e prioriza, lê o teu código-fonte e transforma um pentest de semanas em um ou dois dias, por uns cinquenta dólares a hora. De outro, o Anthropic Mythos, ainda em preview, da Anthropic, a criadora do Claude: ele achou duzentas e setenta e uma vulnerabilidades no Firefox de uma vez, um bug de vinte e sete anos no OpenBSD. É o teto do que a IA já faz por segurança.`,
  ferramentas_gancho: `E olha o gancho que muda o jogo: pentest de nível enterprise por quatrocentos dólares. Aquilo que custava cinquenta mil reais e um mês de trabalho agora cabe num fim de semana. A barreira caiu. Não tem mais desculpa de é caro demais.`,
  kit_dia_a_dia: `Mas calma, você não precisa de nada caro pra começar. Olha o teu kit do dia a dia, grátis ou baratinho. O Security Advisor do Supabase acha RLS aberto em dois minutos. O GitGuardian ou o gitleaks caçam secret vazado no teu Git. O Semgrep mais o Dependabot fazem análise do código e alertam dependência vulnerável. E o Claude ou o GPT auditam o teu RLS e o schema com um único prompt. Com esse kit você já cobre a maior parte do risco.`,
  prompt_auditoria: `E falando em auditar com IA, esse é o prompt que eu mais uso, e você pode começar agora, de graça. Você cola ele no Claude ou no GPT junto com o teu schema e as tuas policies, e ele vasculha procurando RLS aberto, política frouxa, dado exposto. Pausa o vídeo, copia esse prompt, e roda no teu projeto hoje ainda. Sério, é o exercício que mais dá retorno de tudo que eu te mostrei.`,
  lovable_cloud_vs_supabase: `Falando em arquitetura, tem duas formas de ter backend. O Lovable Cloud é o default, zero setup: você liga e usa, vem com auth, banco, storage e edge, e é ótimo até uma produção média. O contra é que você não acessa o dashboard cru. Já o Supabase próprio te dá controle total: dashboard completo, branching, backups, point-in-time, configuração fina. Vale quando os dados crescem. Comece simples com o Cloud, e migre quando fizer sentido.`,
  quando_migrar: `E quando é hora de profissionalizar o backend? Alguns sinais. Queries ficando lentas com mais de dez mil linhas. Necessidade de backup point-in-time, pra voltar no tempo. Time crescendo e precisando de papéis e permissões. Dados regulados, tipo saúde ou financeiro. Ou um SLA com cliente enterprise. Se você marcou um desses, é sinal de que tá na hora de dar o passo. Antes disso, não precisa complicar.`,
  setup_robusto: `Quando migrar, tem quatro configs que mudam o nível de maturidade do teu projeto. PITR, o point-in-time recovery, que deixa você voltar no tempo se algo der errado. Branching, pra ter ambiente de staging por pull request. MFA mais papéis, todo mundo com dois fatores e a role mínima. E observability, logs e alertas no Sentry ou Logflare. Essas quatro coisas separam o hobby do produto sério.`,
  checklist_lancamento: `Antes de apertar o deploy, roda esse checklist de lançamento. RLS ativo em toda tabela, com o Security Advisor no verde. Nenhum secret no front, só anon key no client. Política de privacidade no ar, com a base legal definida. Exclusão de conta funcionando, direito do titular atendido. E MFA mais backup ligados no Lovable, no Supabase e no GitHub. Se todos os cinco tão ok, você lança tranquilo.`,
  checklist_segunda: `E pra você que terminou o curso animado, aqui vão as ações pra colocar em prática hoje mesmo. Ativar o RLS em tudo, começando pelas tabelas com user_id. Rodar o Security Advisor, que leva dois minutos e é grátis. Auditar o RLS com IA, colando o schema no Claude ou no GPT. E ligar MFA em tudo: Lovable, Supabase e GitHub. Quatro ações, uma tarde de trabalho, e o teu app já fica num outro patamar.`,
  curso_proximos: `Você terminou o curso, parabéns mesmo. E agora? Rode o checklist no teu app ainda hoje, não deixa pra depois. Audita o teu RLS com aquele prompt da aula dez. Transforma cada direito do titular num endpoint, um de cada vez. E o mais importante de tudo: segurança não é um estado que você atinge e acabou, é um hábito que você mantém. Volta nessas aulas sempre que precisar.`,
  confianca: `Quero deixar você com uma ideia que resume tudo. O cliente compra a tua funcionalidade. Mas ele fica pela confiança. Segurança e respeito ao dado dele não são burocracia, são o que faz ele voltar e te indicar.`,
  vai_la_proteja: `É isso. Foi um prazer enorme te acompanhar nessas dez aulas. Agora vai lá e protege. Constrói rápido, constrói bonito, mas constrói seguro. Conta comigo, e qualquer dúvida me chama. Um abraço, e até a próxima.`,
};
