// Roteiros de TELEPROMPTER do Bootcamp (parceria Instituto Caldeira, Porto Alegre).
// Deck = o mesmo da Travessia (segurança no vibecoding: Supabase/RLS + LGPD + ferramentas).
// key do slide → fala COMPLETA do apresentador (tom natural, 1ª pessoa, PRESENCIAL/palco).
// Não é pra repetir o que está na tela — é a locução, com exemplos, números e transições.
// Exibido pelo overlay de teleprompter (tecla T).

export const scripts: Record<string, string> = {
  // ─── ABERTURA ───
  cover: `Boa noite, Porto Alegre! Que prazer estar aqui no Instituto Caldeira com vocês. Deixa eu já combinar o que essa palestra NÃO é: não é papo de "usa senha forte, ativa o 2FA". A gente vai falar de uma coisa que pega quase todo mundo que constrói com IA hoje — você monta um app lindo, rápido, no Lovable, coloca no ar… e deixa a porta dos fundos escancarada, sem nem perceber. Nas próximas horas eu vou te mostrar onde mora esse risco, como isso vaza na vida real, e o mais importante: como construir rápido SEM deixar buraco. Bora?`,
  ato_1_porque: `Primeiro ato: o porquê. E eu preciso te convencer de uma coisa logo de cara, senão o resto não gruda — por que dá pra construir rápido sem deixar buracos, e por que a maioria não faz isso.`,
  agenda: `Esse é o mapa da nossa conversa, quatro paradas. Primeiro o "por quê" — o risco que você não enxerga. Depois a gente mergulha no Supabase, que é onde mora quase todo o perigo. Aí sobe pro código e pra LGPD — a parte que assusta, sem juridiquês. E fecha com arquitetura: como escalar sem dor. Qualquer dúvida no meio, levanta a mão que eu paro.`,
  realidade: `Deixa eu começar com um dado que dói. A MAIORIA dos apps gerados com IA que estão em produção agora tem o RLS aberto — o Row Level Security, o cadeado do banco, está destrancado. Não é que está fraco: está DESLIGADO. E o dono não sabe, porque o app funciona lindo mesmo assim.`,
  historia_real: `E olha como isso vaza, é sempre a mesma novela. Sexta você lança no grupo do zap, todo empolgado. Sábado já tem duzentos cadastros, com nome, e-mail, CPF, tudo. Domingo, alguém curioso abre o DevTools do navegador — aquela ferramentinha que todo mundo tem — e vê que dá pra puxar o banco inteiro. Segunda de manhã, sua tabela de clientes tá circulando num fórum. E não precisou de hacker nenhum: precisou de uma policy que faltou.`,
  policy_faltando: `Porque no fundo isso aqui não é um "ataque sofisticado". É uma policy faltando. Uma regra de acesso que ninguém escreveu. Guarda essa palavra — policy — que a gente vai voltar nela.`,
  tres_camadas: `O risco mora em três camadas, e a gente vai passar pelas três hoje. O banco — RLS, edge functions, RPC. O código — secrets, validação, logs. E a governança — LGPD, acessos, backup. A maioria das pessoas só pensa na terceira quando já virou problema. A gente vai começar pela primeira, que é onde o estrago é maior.`,
  ponte_supabase: `Então bora começar pelo banco. É onde mora oitenta por cento do risco — e é onde dá pra resolver oitenta por cento dele.`,

  // ─── ATO 2 · SUPABASE ───
  ato_2_supabase: `Segundo ato: Supabase. Se você constrói no Lovable, o Supabase é o seu backend — e é ali que o dado vive de verdade. Então é ali que você tem que olhar com carinho.`,
  vitrine_deposito: `Deixa eu te dar a analogia que faz a ficha cair. O Lovable é a VITRINE — é o que o usuário vê, clica, a telinha bonita. O Supabase é o DEPÓSITO — é onde a mercadoria, o dado, fica guardada. O ladrão não quebra a vitrine: ele entra pelo depósito. E a maioria das pessoas passa semanas caprichando na vitrine e deixa o depósito de porta aberta.`,
  tres_pilares: `No Supabase, três pilares — e cada um tem um jeito clássico de furar. Tabelas: onde o dado mora, o risco é o RLS aberto. Edge functions: a sua lógica de servidor, o risco é não validar quem está chamando. E RPC, funções dentro do banco, onde o risco é o "SECURITY DEFINER" rodando cego, com poder total. Hoje eu vou focar no primeiro, que é o mais comum. Um aviso pros mais técnicos: naquele RPC com SECURITY DEFINER, sempre fixe o search_path da função — senão dá pra sequestrar quais tabelas ela enxerga, e uma função "segura" vira porta de entrada.`,
  o_que_e_rls: `RLS, Row Level Security, é simplesmente isto: uma regra que decide QUEM vê QUAL linha da tabela. E você define isso pra cada operação — quem pode ver, quem pode criar, quem pode editar, quem pode apagar. É o porteiro do seu banco, linha por linha. Sem ele, todo mundo entra.`,
  rls_aberto: `E aqui está o default perigoso: RLS desativado é porta aberta. Repara nesse cadeado destrancado. Quando o RLS está desligado, qualquer pessoa que tenha a "anon key" — que, atenção, está no código do front, qualquer um vê no navegador — consegue ler o banco INTEIRO. Não é teoria. É o cenário mais comum de vazamento em app vibecoded.`,
  top_riscos_rls: `Esses são os quatro erros que eu mais vejo. Um: RLS desativado na tabela — qualquer um lê tudo com a anon key. Dois: a policy de SELECT igual a "true" — parece que tá protegido, mas liberou pra todo mundo. Três: INSERT sem validar o user_id — o usuário grava dado como se fosse outra pessoa. Quatro: UPDATE ou DELETE sem checar o dono — edita e apaga dado alheio. E ao lado de cada um, o conserto. Não precisa decorar — vou te dar tudo isso no final. E uma fineza pra quem for a fundo: no UPDATE, use USING E WITH CHECK juntos — o USING decide quais linhas você pode editar, e o WITH CHECK impede que você "chute" o dado pra outro dono no meio da edição.`,
  exemplo_ruim: `Olha isso na tela — e não precisa saber SQL pra entender. Essa policy diz "todos veem", usando "USING (true)". "True" significa: verdadeiro pra todo mundo, sempre. Ou seja, qualquer um, logado ou não, vê tudo. O desenvolvedor achou lindo porque "funciona". Funciona pro atacante também. Essa é a porta aberta.`,
  exemplo_bom: `E esse é o jeito certo, quase igual, só que salva a sua pele. Repara na última linha: "USING user_id igual a auth.uid()". O auth.uid() é o ID de quem está logado naquele momento. Então a regra vira: "só te mostro a linha se ela for SUA". Comparou, bateu, passou. Não bateu, não vê. É literalmente uma linha de diferença entre vazar tudo e proteger tudo.`,

  storage_publico: `E tem um segundo cadeado que quase todo mundo esquece: o Storage. A galera capricha no RLS das tabelas e deixa o bucket de arquivos PÚBLICO — aí qualquer um com o link baixa a nota fiscal, o RG, o contrato que o cliente subiu. Presta atenção nisso, porque pega muita gente: o Storage do Supabase tem RLS PRÓPRIO, ele não herda a regra da tabela. A regra de ouro é bucket privado com URL assinada, que expira. Antes de dormir hoje, abre o seu Storage e confere se não tem nenhum bucket público esquecido aberto — é o vazamento mais bobo que existe.`,

  // ─── ATO 3 · CÓDIGO + GOVERNANÇA ───
  ato_3_codigo: `Terceiro ato: saindo do banco, subindo pro código e pra governança. Porque proteger o banco é essencial, mas não é o fim da história.`,
  codigo_vs_supabase: `Vale separar onde cada coisa mora. No lado do código, no Lovable e nas edge functions: validação de input, os secrets no ambiente e nunca no client, rate limit, logs sem dado sensível. No lado do banco, no Supabase: as regras de acesso — RLS, RPC, auth, backup. Cada camada faz a sua parte; nenhuma sozinha resolve.`,
  nao_so_lovable: `E aqui um recado importante: o Lovable ajuda MUITO, mas ele não é tudo. Audita você mesmo com IA — o Claude ou o GPT lê o seu código melhor do que você às vezes. Usa o GitHub como rede de segurança: histórico, rollback, code review. A service_role, aquela chave master, NUNCA vai pro front — só a anon key vai pro cliente. E roda o Security Advisor do Supabase toda semana; é de graça e acha muita coisa.`,

  // ─── SEGURANÇA DE IA (slides extras do bootcamp) ───
  ia_prompt_injection: `Agora, se você colocou — ou vai colocar — um agente de IA no seu app, e no vibecoding isso é quase automático, esse aqui é pra você. Prompt injection é a SQL injection da era dos agentes. Lembra do "ou 1 igual a 1" no login? Aqui é a mesma energia, só que em português: o usuário escreve um texto que o modelo confunde com uma ordem sua, do dono do sistema. E como a IA recebe a instrução e o conteúdo no mesmo lugar, ela tende a obedecer o que soa mais oficial. É o risco número um do OWASP pra aplicações com LLM — o topo da lista.`,
  ia_blindagem: `E como você blinda isso? Quatro princípios — e o primeiro é o que mais gente erra. Autorização no CÓDIGO, nunca no prompt: escrever "não altere papéis" no system prompt não é segurança, é um pedido educado; a ação sensível tem que checar, no servidor, o papel real de quem chamou. Segundo, menor privilégio: não dá pro agente uma ferramenta que muda role ou apaga dado se ele não precisa. Terceiro: todo input do usuário é dado hostil até prova em contrário. E quarto, o fio-terra: o RLS é a sua rede final, e vale até pra IA — se a injeção furar tudo, o dado dos outros ainda não sai. Repara que é a MESMA lição do banco: quem manda é o código, não o texto.`,

  // ─── LGPD ───
  ato_3_lgpd: `Agora a parte que faz o pessoal se remexer na cadeira: LGPD. Mas relaxa — eu prometo, sem juridiquês. Vou te dar só o que muda a sua vida como quem constrói.`,
  lgpd_o_que_e: `LGPD é a lei que diz COMO você pode tratar dado de pessoa. É a Lei 13.709, de 2018, inspirada no GDPR europeu, e ela criou a ANPD — a autoridade que fiscaliza, orienta e multa. E o ponto que todo mundo tenta escapar: se você tratou dado de brasileiro, você está sob a LGPD. Sim, até no MVP. Até no seu projetinho de fim de semana.`,
  lgpd_linha_tempo: `Rapidinho a linha do tempo, só pra situar: sancionada em 2018, entrou em vigor em 2020, e as sanções começaram a valer em 2021. Ou seja, não é novidade e não é "vai que pega" — já está valendo faz tempo.`,
  lgpd_dado_sensivel: `E preciso que você entenda que nem todo dado é igual. Tem o dado pessoal — nome, e-mail, telefone, CPF, IP, qualquer coisa que ligue a uma pessoa. E tem o dado SENSÍVEL, que tem regime reforçado: saúde, biometria, raça, religião, política, orientação sexual. Se vazou dado sensível, o estrago e a multa são muito maiores. Então se o seu app coleta isso, o cuidado tem que ser em dobro. E tecnicamente a régua muda: pra dado sensível NÃO cabe legítimo interesse — as bases do artigo 11 são mais restritas, em geral consentimento específico e destacado, ou hipóteses bem pontuais da lei.`,
  lgpd_pii_escondida: `E aqui vem a pegadinha: você coleta MUITO mais dado pessoal do que imagina. O IP e o user agent, que todo request loga, mesmo sem cadastro. A geolocalização daquele popup de "permitir localização". O device ID do analytics, do push. E o óbvio, e-mail e nome. Tudo isso é PII, é dado pessoal. Você já é um controlador de dados e talvez nem tenha percebido.`,
  lgpd_mito: `E agora eu vou derrubar o maior mito da LGPD, aquele que todo mundo repete errado: LGPD NÃO é só pedir consentimento. Aquele banner de cookie que todo site enfia na sua cara? Na maioria das vezes é teatro, e às vezes até errado.`,
  lgpd_bases_legais: `A lei tem dez bases legais — dez justificativas pra você poder tratar um dado. No SaaS, três importam de verdade. Execução de contrato: o dado é necessário pra entregar o serviço. Legítimo interesse: usos esperados, tipo segurança, antifraude, logs. E consentimento: o extra, o opcional — marketing, cookies não essenciais. Repara: consentimento é a ÚLTIMA da fila, não a primeira. E um adendo pra não tomar susto no Q&A: legítimo interesse não é passe livre — a lei espera que você faça e DOCUMENTE um teste, o tal do LIA, mostrando que o seu interesse não atropela o direito do titular.`,
  lgpd_teste_contrato: `E tem um teste mental que resolve noventa por cento das suas dúvidas. Pergunta: "se eu parar de tratar esse dado, eu ainda consigo prestar o serviço?". Se a resposta é NÃO — tipo o e-mail de login, o endereço de entrega — então a base é execução de contrato, e você não precisa de consentimento pra isso. Simples assim.`,
  lgpd_exemplos_base: `Vamos aterrissar. E-mail e senha? Execução de contrato. CPF na nota fiscal? Contrato. Endereço de entrega? Contrato. Logs e IP pra antifraude? Legítimo interesse. Newsletter e marketing? Aí sim, consentimento. Compartilhar dado com um parceiro comercial? Consentimento, e explícito. Percebe que "pedir aceite" é a exceção, não a regra?`,
  lgpd_aws_q: `Deixa eu fazer uma pergunta pra plateia, e quero que vocês respondam de verdade: quem aqui acha que a AWS, a Amazon, precisa do SEU consentimento pra guardar o e-mail do seu login na conta deles? Levanta a mão quem acha que sim.`,
  lgpd_aws_a: `Pois é. Se precisasse, a internet simplesmente não funcionaria. Cada login, cada request, teria um popup pedindo aceite. Não tem — porque a base ali é execução de contrato. Guarda essa imagem.`,
  lgpd_frase_efeito: `Então fica a frase pra levar pra casa: a LGPD não exige consentimento. Ela exige uma BASE LEGAL válida. Consentimento é só uma das dez, e geralmente nem é a que você precisa.`,
  lgpd_onde_mora_risco: `Agora, onde mora o risco DE VERDADE, aquilo que dá multa? Usar o dado pra um marketing que a pessoa não esperava. Compartilhar com um parceiro comercial sem avisar. Treinar uma IA sua com o dado do cliente. Enfim — qualquer uso que o usuário não espera. Não é ter o dado; é usar pra uma finalidade que ele não imaginava.`,
  lgpd_transparencia: `E cuidado com esse pulo do gato: não precisar de consentimento NÃO quer dizer que você pode esconder. O erro é pensar "não preciso pedir aceite, então nem aviso". O certo é: informa com clareza na política de privacidade, deixa a base legal explícita, garante os direitos do titular — mas não precisa ficar pedindo aceite pra tudo. Transparência é obrigatória sempre.`,
  lgpd_controlador_operador: `E esse é o tema que todo SaaS confunde: controlador versus operador. O controlador decide o porquê e o como — tipo a escola que cadastra os alunos. O operador trata o dado em nome do controlador — geralmente é o SEU SaaS, processando o dado do cliente. MAS atenção: no minuto em que você usa aquele dado pra analytics ou pra treinar uma IA SUA, você vira controlador também. Dá pra ser os dois ao mesmo tempo — e a responsabilidade muda.`,
  lgpd_basico: `Resumindo o essencial: se você guarda dado de brasileiro, a LGPD vale pra você. O que muda na prática? Escolher a base legal certa, informar o que coleta e por quê, e responder aos pedidos do titular. E se ignorar? A multa da ANPD pode chegar a dois por cento do faturamento, com teto de cinquenta milhões por infração — sem contar bloqueio do tratamento, dano moral coletivo, e virar capa de jornal num print.`,
  lgpd_quanto_custa: `E não é conversa pra te assustar de mentira. Ignorar isso tem preço — e vira manchete. Deixa eu te mostrar uns números reais.`,
  lgpd_multa_recorde: `A maior multa de proteção de dados da história: um bilhão e duzentos milhões de euros. Na Meta, dona do Facebook, em 2023, por mandar dados de europeus pros Estados Unidos sem base legal. Um bilhão e duzentos milhões. Isso não é multinha de trânsito.`,
  lgpd_casos_reais: `E não foi só a Meta. Amazon: setecentos e quarenta e seis milhões de euros, por publicidade sem consentimento válido. TikTok: trezentos e quarenta e cinco milhões, por dados de crianças mal protegidos. E aqui no Brasil, pra você ver que chega: a Telekall levou a primeira multa da ANPD em 2023, por vender uma lista de WhatsApp. Foi "só" catorze mil reais — mas foi o começo.`,
  lgpd_brasil_hoje: `E no Brasil, hoje? A multa ainda é tímida, o estrago não. A ANPD ainda está amadurecendo — primeira multa só em 2023, mas já endureceu a partir de 2024, e em 2025 soltou a Nota Técnica 12, mirando justamente IA e decisão automatizada. Agora, o que dói de verdade não espera a ANPD: lembra do Serasa, mais de duzentos e vinte milhões de CPFs vazados? Ação civil, dano moral coletivo, e a sua reputação destruída num único print. A conta chega por vários caminhos.`,
  lgpd_cyber: `E é por isso que eu junto as duas coisas nessa palestra: LGPD é governança de dados. Mas governança sem cybersecurity é só um PDF bonito. Sem proteger tecnicamente — sem RLS, sem secret guardado — a sua conformidade não existe na prática. As duas andam juntas.`,
  direitos_titular: `O artigo 18 dá seis direitos ao titular, e o legal é que cada um vira CÓDIGO no seu app. Acessar — ver tudo que você tem dele. Corrigir. Portar — exportar pra outro serviço. Revogar o consentimento. Excluir — apagar conta e dados. E o sexto, que casa com tudo que a gente falou de IA: revisar decisão automatizada — contestar o que a IA decidiu sobre ele. Isso não é filosofia; é endpoint.`,
  lgpd_vira_codigo: `E na prática, como a LGPD vira código no Supabase? Exclusão: uma edge function que apaga a conta e os dados. Portabilidade: um endpoint que exporta em JSON ou CSV. Minimização: não logar PII, usar views mascaradas. Consentimento: uma tabela "consents" com timestamp e versão. E incidente: um alerta que dispara pra você avisar a ANPD e os titulares no prazo. É tudo implementável — e a maior parte é simples.`,
  governanca_acessos: `E governança também é definir quem acessa o quê. Olha uma matriz mínima de papéis. O vendedor vê só os leads dele — RLS por owner. O gerente vê o time todo e exporta relatórios. O marketing precisa do e-mail e da tag, mas NÃO precisa do CPF nem do valor do negócio — então entra com uma view mascarada. E você, o builder: cuidado, porque a service_role no seu .env dá bypass total da RLS. Ela só pode viver na edge function, nunca no client, e com MFA sempre.`,

  // ─── MARCO LEGAL DA IA (slide extra do bootcamp) ───
  marco_legal_ia: `E não para na LGPD — tá vindo mais. O Marco Legal da IA, o PL 2338, já passou no Senado e está em votação final na Câmara, com previsão de fechar em 2026. Ele segue o modelo europeu, o AI Act: classifica a inteligência artificial por nível de risco, e garante ao cidadão o direito de explicação e de contestar uma decisão automatizada — que é exatamente o artigo 20 que a gente acabou de ver. Cria uma governança nacional de IA, o SIA, e de novo prevê multa de até cinquenta milhões. O recado é esse: o que hoje é boa prática, amanhã é lei. Quem já constrói pensando nisso larga na frente.`,

  // ─── FERRAMENTAS & DICAS ───
  ferramentas_intro: `Chega de assustar — bora pra parte boa. O arsenal. E a notícia excelente é essa: a mesma IA que ataca também defende. E ficou barata.`,
  ferramentas_principais: `Olha a artilharia pesada de 2026. De um lado, o AWS Security Agent — um pentest autônomo, multi-agente, que lê o seu código-fonte e faz em um ou dois dias o que um humano levaria semanas. Isso já está disponível, é GA, custa cerca de cinquenta dólares a hora. Do outro lado, o Claude Mythos, da Anthropic — que é a criadora do Claude, não a AWS. Esse é o teto do que a IA já faz: achou sozinho milhares de zero-days em vários sistemas, um bug de vinte e sete anos no OpenBSD, um RCE de dezessete anos no FreeBSD. É tão poderoso que ainda está fechado, em preview. A capacidade que antes era de elite virou commodity.`,
  ferramentas_gancho: `Pra dar a dimensão: um pentest de nível enterprise, que custava cinquenta mil reais e um mês de trabalho, hoje cabe em uns quatrocentos dólares e num fim de semana. A barreira de entrada da segurança despencou. Não dá mais pra dizer "segurança é caro, fica pra depois".`,
  kit_dia_a_dia: `E pro seu dia a dia, um kit que é grátis ou quase. O Security Advisor do Supabase acha RLS aberto em dois minutos e agora até testa as suas policies. O próprio Lovable, na versão 2.0, tem um Security Scan que varre o app e aponta risco. GitGuardian e gitleaks caçam secret vazado no Git. Semgrep e Dependabot cuidam do código e das dependências. E o mais democrático de todos: cola o seu RLS e o schema no Claude ou no GPT e pede uma auditoria. Custa um prompt.`,
  prompt_auditoria: `E é exatamente esse prompt que está aqui na tela. Não tenta ler tudo daqui de trás — o importante é a ideia: você entrega pra IA o seu schema e as suas policies e pede pra ela achar o RLS aberto, o dado exposto, o furo. Vou deixar esse prompt pra vocês levarem — tira uma foto agora se quiser, mas ele vai estar disponível. O recado é: dá pra fazer isso HOJE à noite, de graça.`,

  // ─── ATO 4 · ARQUITETURA ───
  ato_4_arquitetura: `Último ato: arquitetura. Como sair do "funciona" e chegar no "escala sem dor" — sem virar noite e sem quebrar em produção.`,
  arquitetura_camadas: `Deixa eu amarrar tudo num desenho mental que você leva pra vida. Toda arquitetura segura tem três fronteiras de confiança. O front, o que o Lovable gera: nunca confie nele — tudo ali é público e manipulável, qualquer um abre o DevTools. A edge function no meio: é ela que VALIDA o input e AUTORIZA, checando quem de fato está chamando. E o banco, o Supabase, com RLS como rede final — a última linha, que nem a IA atravessa. Front não confia, edge valida, banco protege. Se você sair daqui só com essa frase, já valeu a noite.`,
  lovable_cloud_vs_supabase: `Duas formas de ter backend, e as duas são válidas. O Lovable Cloud é o default: liga e usa, já vem auth, banco, storage, edge — ótimo até uma produção média, sem você mexer em nada cru. O Supabase próprio te dá controle total: dashboard completo, branching, backup point-in-time, ajuste fino de índices e pooling. A regra: comece no Cloud pela velocidade, migre pro próprio quando os dados crescerem ou o cliente exigir.`,
  quando_migrar: `E como saber a HORA de profissionalizar? Alguns sinais: queries começando a ficar lentas com mais de dez mil linhas. Necessidade de backup point-in-time. Time crescendo, precisando de papéis. Dados regulados — saúde, financeiro. Ou um SLA com cliente enterprise. Bateu um desses? É hora de subir o nível da infra.`,
  setup_robusto: `E o que muda a maturidade da sua infra são quatro configs. PITR, o point-in-time recovery, que te deixa voltar no tempo depois de um erro. Branching, um ambiente de staging por pull request. MFA e papéis — todo mundo com dois fatores ou passkey, e a role mínima necessária. E observability: logs e alertas num Sentry ou Logflare, pra você saber do problema antes do cliente.`,
  checklist_segunda: `E pra isso não virar só palestra bonita, quatro ações pra segunda de manhã. Ativa o RLS em tudo — começa pelas tabelas com user_id. Roda o Security Advisor, dois minutos, de graça. Audita o RLS com IA, colando o schema no Claude ou GPT. E liga MFA em tudo — Lovable, Supabase, GitHub. Faz esses quatro essa semana e você já sai da maioria absoluta que está exposta.`,
  confianca: `E eu quero fechar com a ideia que, pra mim, é a mais importante de tudo. O cliente compra a sua funcionalidade — ele entra pelo que o app FAZ. Mas ele FICA pela confiança. Um vazamento não quebra só um banco de dados; quebra a relação. Segurança não é custo, é o que sustenta tudo que você construiu.`,
  vai_la_proteja: `Então é isso, Caldeira. Você já sabe construir rápido. Agora você sabe construir sem deixar a porta aberta. Vai lá — e protege. Muito obrigado!`,
};
