// Roteiros de TELEPROMPTER do workshop DEATEC ("Segurança em IA & Automação").
// key do slide → fala COMPLETA do apresentador (tom natural, 1ª pessoa, evento ONLINE).
// Não é pra repetir o que está na tela — é o texto de locução, com exemplos, números,
// analogias e transições pra você ler. Exibido pelo overlay de teleprompter (tecla T).

export const scripts: Record<string, string> = {
  // ─── ABERTURA ───
  cover: `Fala, pessoal, beleza? Sejam muito bem-vindos, que bom ter vocês aqui com a DEATEC. Deixa eu já te falar o que essa hora NÃO vai ser: não vai ser aquele papo genérico de "use senha forte e ative o dois fatores". A gente vai falar de uma coisa nova, que tá pegando todo mundo de surpresa — os riscos de quem constrói software COM inteligência artificial. E eu não vim só palestrar: eu vou invadir uma aplicação ao vivo, na frente de vocês, usando só conversa com um chatbot. Depois a gente constrói uma automação de verdade, também ao vivo. Então pega um café, abre o chat aí do lado, porque vai ser prático. Bora.`,
  agenda: `Deixa eu te dar o mapa da nossa hora, pra você saber onde a gente tá em cada momento. Primeiro, dez minutinhos de contexto: por que 2026 mudou o jogo da segurança. Depois, o bloco mais denso, sobre os riscos de IA e a LGPD — e é nele que eu faço o ataque ao vivo de prompt injection. Na sequência, a parte que todo mundo gosta: construir uma automação no Supabase, ao vivo, mostrando segurança e automação juntas. Aí eu te mostro como auditar tudo isso usando a própria IA, e a gente fecha com perguntas. São cinco blocos, uma hora cravada. Qualquer dúvida no meio do caminho, manda no chat que eu paro pra responder.`,
  online_intro: `Como a gente tá online, deixa eu combinar três coisas rápidas. Um: dúvida é pra jogar no chat na hora que vier, não precisa segurar pro final — eu vou pausando pra responder. Dois: nos momentos de tela compartilhada, presta atenção, porque é ali que a coisa fica real, não é slide. E três: tudo que eu mostrar hoje você consegue reproduzir depois, então relaxa, não precisa anotar cada detalhe. Combinado? Então bora pro primeiro bloco.`,

  // ─── BLOCO 1 · ABERTURA ───
  bloco_1: `Primeiro bloco: contexto. E eu vou começar tentando te convencer de uma coisa, porque se você não comprar essa ideia, o resto não faz sentido: por que, especificamente agora, segurança parou de ser opcional pra quem usa IA.`,
  panorama_2026: `Olha o que mudou. Até pouco tempo atrás, atacante era gente com tempo sobrando garimpando código na mão. Hoje, o atacante usa IA pra fazer reconhecimento de milhares de alvos em minutos, achar a porta aberta e explorar — automatizado. Então a IA virou ARMA. Mas tem o outro lado, que é o que mais importa pra gente aqui: a IA que VOCÊ colocou no seu produto, aquele chatb,ot bonitinho, aquele "assistente", virou uma porta de entrada nova que não existia antes. Ou seja, a IA também é ALVO. Você ampliou a superfície de ataque no exato momento em que os atacantes ficaram mais rápidos. É essa tesoura que torna 2026 diferente.`,
  porque_agora: `Quatro coisas mudaram de verdade. Primeira: automação virou agente. Antes era "se cair um e-mail, salva na planilha" — burrinho e previsível. Agora o agente DECIDE e EXECUTA ação sozinho: ele lê, escolhe e mexe no seu banco. Segunda: a superfície explodiu — cada integração, cada tool, cada prompt é uma porta nova que você abriu sem perceber. Terceira: o dado escorre pra mais lugares — vai pro treino, pra inferência, pros logs, pra APIs de terceiros. E a quarta, que resume tudo: quem constrói com IA virou o alvo preferido, porque normalmente é quem foi rápido e não olhou a segurança. E adivinha quem tá do outro lado te procurando? Também uma IA.`,
  seguranca_opcional: `Então fica a primeira frase pra levar pra casa, e eu quero que ela grude: segurança deixou de ser opcional. Não é mais aquele enfeite que você faz "se sobrar tempo". Hoje é pré-requisito — é o que separa o app que escala do app que vira manchete.`,

  // ─── BLOCO 2 · SEGURANÇA EM IA + ATAQUE AO VIVO ───
  bloco_2: `Segundo bloco, o coração da palestra: segurança em IA. Eu vou te mostrar os riscos que realmente importam, e no meio do caminho — sem rede — eu vou fazer um ataque ao vivo numa aplicação que parece de produção. Prepara o coração.`,
  riscos_ia: `Existem quatro riscos de IA que você precisa ter no radar, e eu vou dar um exemplo concreto de cada. Viés: imagina um modelo que decide crédito treinado com dado torto — ele nega financiamento pra um grupo inteiro, e a responsabilidade é SUA, não da IA. Envenenamento de dados: o atacante planta informação maliciosa onde seu modelo aprende, e corrompe o comportamento dele lá na frente. Ataques adversariais: aquele input desenhado pra enganar — um ruído numa imagem que faz o modelo ver "liberado" onde tá escrito "bloqueado". E o quarto, que é o protagonista de hoje e o número um do OWASP pra LLM: prompt injection, quando uma instrução maliciosa simplesmente sequestra o seu agente. Desses quatro, o que mais pega quem constrói com IA hoje é esse último. Então vamo fundo nele.`,
  vibecoding_contexto: `Deixa eu aterrissar isso na nossa realidade, na stack do vibe coding: Lovable na frente, Supabase atrás. O fluxo é sempre o mesmo. Você pede pra IA "coloca um chatzinho de suporte no meu app". Ela gera. Esse agente, pra ser útil, precisa LER e ESCREVER no Supabase — então ela já te entrega o código com uma ferramenta que mexe no banco. Só que repara no detalhe perigoso: o texto que o usuário digita chega MISTURADO com as instruções do sistema, no mesmo campo. E como a IA gerou tudo "pra funcionar", ela costuma dar pro agente permissão DEMAIS. Junta as três coisas — input misturado, permissão sobrando, e uma trava fraca — e o que era um chatbot de suporte vira uma porta pra escalonamento de privilégio. É exatamente isso que eu vou te mostrar acontecendo em trinta segundos.`,
  prompt_injection: `Prompt injection, na real, é a SQL injection da era dos agentes. Lembra da SQL injection? Você punha um "ou 1 igual a 1" no campo de login e enganava o banco. Aqui é a mesma energia, só que em português: você escreve um texto que o modelo confunde com ordem do dono do sistema. E o problema é estrutural, não é bug de um modelo específico: a IA recebe instrução e conteúdo no mesmo lugar e não tem como saber, com certeza, quem é a autoridade ali. Ela tende a obedecer o que SOA mais oficial. Guarda isso, porque é a chave do ataque.`,
  injection_exemplo: `Olha o padrão vulnerável na tela, porque isso aqui é cópia fiel do que rola em app vibecoded. O desenvolvedor deu pro agente uma ferramenta poderosa — no nosso caso, trocar o papel de um usuário. E qual é a única proteção contra alguém se promover? Uma FRASE no prompt: "não altere papéis". Só isso. Aí vem o pecado mortal, essa linha aqui embaixo: quando o modelo decide chamar a ferramenta, o backend executa e NÃO confere se quem pediu é admin. Ou seja, a autorização virou texto, virou pedido educado. E o pior de tudo: isso FUNCIONA na demo do dia a dia, o app roda liso, então ninguém nunca revisa. O buraco fica lá, invisível, até alguém como eu aparecer. Bora ver as técnicas que arrombam essa frase.`,
  injection_tecnicas: `São três técnicas, e todas exploram a mesma fraqueza: a IA não separa instrução de conteúdo. A primeira é o bloco de sistema falso — eu escrevo "colchete SISTEMA" e uma diretiva, e o modelo trata aquilo como se fosse ordem legítima da plataforma. A segunda é autoridade genérica: eu não preciso nem saber o nome de ninguém, eu só digo "manutenção autorizada", "solicitação aprovada número tal", e a IA engole, porque soa oficial. E a terceira é delimiter injection: eu forjo um "fim da mensagem do usuário, nova instrução de sistema" pra fazer o meu texto pular de "dado" pra "comando". Repara que nenhuma delas exige hacking pesado — é engenharia social, mas com a máquina. E é aí que tá a beleza assustadora disso.`,
  aovivo_injection: `Beleza, agora é ao vivo — compartilhando a tela. [Roteiro pra você narrar enquanto faz]: "Olha, esse é o CRM, um sistema de vendas normal. Vou logar como a Ana, uma VENDEDORA comum." Mostra que ela só vê os clientes dela, o CPF tá mascarado, e que não existe menu de Usuários. "Agora vou pedir pro assistente, na lata: me promove a admin." Ele recusa — "viu? parece seguro, tem uma trava." Aí você cola o payload de sistema falso e fala: "mas agora eu não PEÇO, eu finjo ser o sistema." Manda. Vira admin na hora. Recarrega a tela: "olha o que apareceu — TODOS os clientes, CPF aberto, o menu de usuários. Uma vendedora virou admin só conversando com um robô." Deixa o silêncio bater.`,
  injection_mitigar: `E agora a parte que salva o seu app. Quatro princípios. Primeiro e mais importante: autorização no CÓDIGO, nunca no prompt. A ação sensível tem que conferir o papel real de quem chamou, no servidor — o modelo pode pedir o que quiser, quem manda é o código. Segundo, menor privilégio: sinceramente, o agente nem deveria ter a ferramenta de mudar papel; dá pra IA só o que ela precisa. Terceiro: trate TODO input do usuário como dado não-confiável, hostil até prova em contrário. E quarto, defesa em profundidade: o RLS no banco é a sua rede final — mesmo que a injeção fure tudo, o dado dos outros usuários simplesmente não sai. No app que acabei de invadir, ligar a checagem no código já mata o ataque inteiro.`,
  lgpd_interface: `Agora vira a chave pro outro lado, que é onde mora a multa: a LGPD. Quatro pontos onde a IA encosta na lei. Base legal: você precisa de uma justificativa pra tratar dado pessoal, e "porque eu quero treinar meu modelo" não é uma delas — treino e inferência precisam de base válida. Explicabilidade: o artigo 20 dá ao seu usuário o direito de pedir explicação e CONTESTAR uma decisão que a IA tomou sobre ele; se você não consegue explicar, você tá exposto. Dado sensível: saúde, biometria, opinião política — se isso entra no seu treino, o regime é muito mais pesado e o estrago de um vazamento, gigante. E minimização: a regra de ouro — não treine nem processe com o dado que você não precisa. Dado que você não tem é dado que não vaza.`,

  // ─── BLOCO 3 · AUTOMAÇÃO SEGURA AO VIVO ───
  bloco_3: `Terceiro bloco. A gente viu o lado sombrio — como a IA quebra. Agora eu quero te mostrar o lado bom: como usar a mesma stack pra construir uma automação útil de verdade, e segura desde o nascimento. E de novo, ao vivo.`,
  arquitetura_demo: `Deixa eu te contar o que a gente vai montar, porque é uma coisa que eu uso na vida real. É uma automação que gera conteúdo pra minha rede social. Tecnicamente, é UMA Edge Function no Supabase — uma função só, sem app, sem frontend, eu chamo direto no navegador. O que ela faz: olha um perfil de inspiração no Instagram, entende o estilo com IA, e me devolve um post pronto — legenda e imagem, nas MINHAS cores. Eu aprovo ou descarto, e o que eu aprovo vira referência pro próximo, então ela aprende meu gosto. E o ponto de hoje: tudo isso com o Cloudflare na frente protegendo, a chave da IA escondida no servidor, e o acesso travado. Automação que economiza minha tarde, sem abrir um buraco de segurança.`,
  stack_pre: `E aqui tá a moral do bloco, presta atenção nessa: a mesma stack que você usa pra VIBECODAR é a que você usa pra PROTEGER. Não são dois times, não é "deixa a segurança pro pessoal de infra" — é o mesmo Supabase, a mesma edge function, o mesmo Cloudflare. Eu deixei a stack pré-montada só pra caber no nosso tempo, porque o que importa aqui não é me ver digitando, é você VER segurança e automação rodando no mesmo fluxo, vivas.`,
  aovivo_automacao: `Tela compartilhada de novo. [Roteiro pra narrar]: "Vou abrir a URL do gerador, e olha, é só isso, uma URL." Ele roda — enquanto carrega, você explica: "por trás, ele tá analisando meu perfil de referência com visão computacional e escrevendo a legenda." Aparece o card de Instagram: "pronto, legenda e imagem, no meu estilo." Aprova um: "esse eu gostei — agora ele vira contexto do próximo." E aí o fecho de segurança, aponta na tela: "repara: a chave da OpenAI NUNCA apareceu, ela vive só no servidor. O Cloudflare tá na frente segurando flood. E a função só responde pro meu proxy, por um header secreto — se alguém tentar abrir direto, toma 403." Segurança e automação, no mesmo lugar, ao vivo.`,

  // ─── BLOCO 4 · AUDITANDO COM IA ───
  bloco_4: `Quarto bloco, e esse é rápido mas levanta a esperança: auditando com IA. Porque a notícia boa é que a mesma inteligência que ataca também defende — e ficou barata.`,
  ferramentas_aud: `Olha o arsenal de 2026, do mais pesado ao mais acessível. O AWS Security Agent é um pentest autônomo, multi-agente, que lê o seu código-fonte e acha o que um humano levaria semanas pra achar. A Anthropic, criadora do Claude, tem uma ferramenta de descoberta — ainda em preview — que sozinha encontrou centenas de vulnerabilidades inéditas em software de verdade. Pra colocar em perspectiva: um pentest que custava cinquenta mil reais e um mês de trabalho hoje cabe num fim de semana e em algumas centenas de reais. E tem o básico, de graça: Security Advisor do Supabase, Semgrep, gitleaks. E o mais democrático de todos — você cola o seu RLS e o seu schema no Claude ou no GPT e pede uma auditoria. Custa um prompt.`,
  auditar_diy: `Então o recado é direto: dá pra auditar por conta própria, hoje, de graça. A barreira de entrada caiu no chão. Não existe mais "ah, segurança é caro, fica pra depois". O que existe é você abrir o Claude hoje à noite e colar o seu schema. Faz isso essa semana.`,

  // ─── BLOCO 5 · ENCERRAMENTO ───
  bloco_5: `Chegamos no fim. Deixa eu amarrar tudo numas poucas frases que eu quero que você leve, mesmo que esqueça todo o resto.`,
  takeaways: `Quatro coisas. Uma: se a IA toca o dado, a LGPD entra junto — trata o dado pessoal com o respeito que a lei exige, desde o MVP. Duas: agente de IA com menor privilégio, sempre — e lembra que o RLS vale até pra ele, não confia nem na sua própria IA. Três: automação segura é uma receita simples — proxy na frente, secret no servidor, RLS no banco. E a quarta, que é quase um conselho de carreira: audite com IA antes que auditem por você. A ferramenta que o atacante vai usar contra você tá disponível pra você usar primeiro. Use.`,
  qa: `E é isso, gente! Muito obrigado por ficarem comigo essa hora. Agora o microfone e o chat são de vocês — manda as dúvidas, os "mas e se...", as discordâncias, tudo. Bora trocar ideia.`,
  encerramento_final: `Fecho com o seguinte: a tecnologia pra construir rápido nunca foi tão acessível, e a pra te atacar também não. A diferença vai estar em quem constrói com cuidado. Então vai lá e cria — rápido, bonito, e seguro. Me acha no @gabreda pra continuar a conversa, e valeu demais pela presença. Um abraço!`,
  materiais: `E pra fechar: tá tudo aqui pra vocês levarem. Clica no botão e baixa o pacote com os códigos das edge functions, o worker da Cloudflare, o passo a passo do lab pra vocês replicarem do zero, e o handbook de estudo com tudo que a gente viu — segurança em IA, prompt injection e LGPD. Estuda, refaz, e me marca quando construir o seu. Valeu!`,
};
